[package]
name = "yew-app"
version = "0.1.0"
authors = ["mitchgollub <mgollub@live.com>"]
edition = "2018"


[dependencies]
strum = "0.19"
strum_macros = "0.19"
serde = "1"
serde_derive = "1"
wasm-bindgen = "0.2.67"
yew = "0.17"

[lib]
crate-type = ["cdylib", "rlib"]