[package]
name = "todo_models"
version = "0.1.0"
authors = ["mitchgollub <mgollub@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1.0"